package com.tw;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public void printMainInterface(){
        System.out.print("1. 添加学生\n" +
                "2. 生成成绩单\n" +
                "3. 退出\n" +
                "请输入你的选择（1～3）：\n");
    }

    public void printAddStudentInterface(){
        System.out.print("请输入学生信息（格式：姓名, 学号, 学科: 成绩, ...），按回车提交：\n");
    }

    public void printGenerateTranscriptInterface(){
        System.out.print("请输入要打印的学生的学号（格式： 学号, 学号,...），按回车提交：\n");
    }
}
